name: mixture_of_diffusers
dependencies:
  - pip=22.1.*
  - pip:
    - diffusers[torch]==0.7.*
    - ftfy==6.1.*
    - gitpython==3.1.*
    - ligo-segments==1.4.*
    - torchvision=0.14.*
    - transformers==4.21.*
